version: '2.0'

services:

  beringei:
    image: gcr.io/mist-ops/beringei:plain
    command: "./beringei/service/beringei_main -beringei_configuration_path /tmp/beringei.json -create_directories -sleep_between_bucket_finalization_secs 60 -allowed_timestamp_behind 300 -bucket_size 600 -buckets 144 -logtostderr -v=2"
    hostname: beringei
    ports:
      - 9999:9999
    volumes:
      - .compose/beringei.json:/tmp/beringei.json

  beringei-http:
    image: gcr.io/mist-ops/beringei:plain
    command: ./beringei/tools/plain_text_service/beringei_plain_text_service -beringei_configuration_path /tmp/beringei.json -ip 0.0.0.0 -http_port 9990
    ports:
      - 9990:9990
    volumes:
      - .compose/beringei.json:/tmp/beringei.json
    depends_on:
      - beringei

  rabbitmq:
    image: rabbitmq:3.6.6-management
    ports:
      - 5672:5672
      - 15672:15627

  graphite:
    image: nickstenning/graphite
    ports:
      - 8080:80
      - 2003:2003
      - 2004:2004
      - 7002:7002

volumes:
  beringei-config: {}

  # gocky:
  #   image: gcr.io/mist-ops/gocky:v0.5
  #   ports:
  #     - 9097:9097
  #   volumes:
  #     - .compose/config.toml:/congig.toml
  #   depends_on:
  #     - beringei
  #     - beringei-http
  #     - rabbitmq
